# Generated by Django 4.1.7 on 2023-04-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.EmailField(max_length=25, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('user', models.CharField(max_length=25, verbose_name='用户名')),
                ('password', models.CharField(max_length=125, verbose_name='密码')),
                ('authority', models.IntegerField(choices=[(0, '普通用户'), (1, 'VIP用户'), (2, '员工')], default=0, verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='验证信息')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25, verbose_name='员工编号')),
                ('name', models.CharField(max_length=5, verbose_name='员工姓名')),
                ('position', models.CharField(max_length=6, verbose_name='职位')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='邮箱')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.merchants', verbose_name='所属商家')),
            ],
            options={
                'unique_together': {('number', 'merchant')},
            },
        ),
    ]
