# Generated by Django 4.1.7 on 2023-04-14 09:59

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='修改')),
                ('txt', models.CharField(max_length=125, verbose_name='操作说明')),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('number', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='商家编号')),
                ('name', models.CharField(max_length=12, verbose_name='商家名称')),
                ('address', models.CharField(max_length=25, verbose_name='商家地址')),
                ('latlon', models.CharField(max_length=52, verbose_name='经纬度')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('num', models.SmallIntegerField(verbose_name='购买数量')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='支付金额')),
            ],
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25, verbose_name='商品编号')),
                ('name', models.CharField(max_length=12, verbose_name='商品名称')),
                ('num', models.SmallIntegerField(verbose_name='商品库存数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品单价')),
                ('kind', models.CharField(max_length=12, verbose_name='商品类型')),
                ('position', models.CharField(max_length=12, verbose_name='商品位置')),
                ('img', models.ImageField(upload_to=home.models.img_path, verbose_name='商品图片')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.merchants', verbose_name='所属商家')),
            ],
        ),
    ]
